### PR TITLE
Add Website

### PR DESCRIPTION
**Pull request by wannaphong**
Add Web Site

### CODE REVIEW

**Comment by heytitle** [comment]
It would be good if we use a static site generator.

**Comment by wannaphong** [comment]
> static site generator.

Can you recommend a static site generator for me?

**Comment by heytitle** [comment]
maybe we can also use `sphinx` here.

**Comment by wannaphong** [comment]
> 
> 
> maybe we can also use `sphinx` here.

I think now would be sufficient to meet demand without having to use a static site generator.

**Comment by heytitle** [comment]
sure but imho it's also good to set everything now because the project isn't that complex.

**Comment by wannaphong** [comment]
I tried to find a way to do it from a static site generator but I didn't find how to use it in this project. I think we should discuss this topic after accepting this pull request.

**Pull request merged**
